# Generated by Django 2.2.13 on 2021-08-26 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('banner', models.ImageField(upload_to='category/banner')),
                ('has_father', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category_father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_article.Category')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
