# Generated by Django 2.2.13 on 2021-08-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('publication_date', models.DateTimeField(editable=False, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='sponsor/banner/')),
                ('type', models.TextField(max_length=50)),
                ('fb_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Staff')),
            ],
        ),
    ]
