# Generated by Django 2.2.13 on 2021-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_auto_20210811_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='appear_home',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
