# Generated by Django 2.2.13 on 2021-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='appear_home',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
