# Generated by Django 2.2.13 on 2021-08-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210813_1410'),
        ('article', '0004_auto_20210813_0318'),
    ]

    operations = [
    ]
