# Generated by Django 2.2.13 on 2021-08-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=5000)),
                ('date_register', models.DateTimeField(editable=False)),
                ('date_last_update', models.DateTimeField(null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='article/banner/')),
                ('link_event', models.CharField(max_length=1000)),
                ('link_form', models.CharField(max_length=500)),
                ('number_participants', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_responsable', to='authentication.Staff')),
                ('user_last_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user_last_update', to='authentication.Staff')),
                ('user_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user_register', to='authentication.Staff')),
            ],
        ),
    ]
