# Generated by Django 2.2.13 on 2021-08-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='responsable',
            new_name='responsible',
        ),
    ]
