# Generated by Django 2.2.13 on 2021-08-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210811_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_last_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user_last_update', to='authentication.Staff'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user_register', to='authentication.Staff'),
        ),
    ]
