# Generated by Django 2.2.13 on 2021-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210813_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateField(default='2021-08-14'),
            preserve_default=False,
        ),
    ]
