# Generated by Django 2.2.13 on 2021-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(),
        ),
    ]
