# Generated by Django 2.2.13 on 2021-08-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210814_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_whatsapp_group',
            field=models.CharField(default='https://chat.whatsapp.com/J8eLRREzsOk0qUvAfqLMdS', max_length=1000),
            preserve_default=False,
        ),
    ]
