# Generated by Django 2.2.13 on 2021-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_link_whatsapp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_user',
            field=models.BooleanField(default=True),
        ),
    ]
