# Generated by Django 2.2.13 on 2021-08-11 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('banner', models.ImageField(upload_to='word_category/banner')),
                ('register_date', models.DateTimeField(editable=False, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('register_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_author_wc', to=settings.AUTH_USER_MODEL)),
                ('update_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_author_wc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(max_length=1000)),
                ('register_date', models.DateTimeField(editable=False, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word_Category')),
                ('register_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_author_w', to=settings.AUTH_USER_MODEL)),
                ('update_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_author_w', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
