# Generated by Django 2.2.13 on 2021-08-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_category',
            name='show_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='words',
            name='show_user',
            field=models.BooleanField(default=True),
        ),
    ]
